### ISSUE TITLE
orix demos 0.5.0

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix-demos#14]
Needs updating:
- [x] 4. Manipulating data in...

**Comment by hakonanes** [comment]
I haven't checked the other notebooks.

**Comment by SteffenBrinckmann** [comment]
# for demo 04:
1. All __setitem__ do not work anymore (sigma, chi)
E.g.: cm.phases["sigma"] = "4/mmm"
     AttributeError: __setitem__
2. "from orix.symmetry import get_point_group" should have a quaternion in it
3. The path should be:
datadir = 'data/04/'

# for demo 02
the file misori_.npy is missing

# for demo 03
the filename ./data/misori-distance((100, 200)).npy should not have the mis

# demo 1 is working perfectly

**Comment by hakonanes** [comment]
Hi Steffen, I assume you're using orix v0.5?

Thanks for this, I'll update the 04 notebook today and see if I can do 02 and 03 as well, although I didn't write these and haven't used them myself.

**Comment by SteffenBrinckmann** [comment]
Hey Hakonanes,
I use '0.5.1-dev', cloned from github
Also the progress bar: tqlr is not working perfectly

**Comment by hakonanes** [comment]
@SteffenBrinckmann, I've made necessary changes in the above linked PR.

Commenting on your comments:

demo4:

* When adding a diffpy.structure SpaceGroup object to `Phase.space_group` in v0.5, the old method of adding a phase to a `PhaseList` became insufficient. We therefore went for a `PhaseList.add()` method (https://orix.readthedocs.io/en/stable/reference.html#orix.crystal_map.phase_list.PhaseList.add).
* The module structure of orix (vector, quaternion, crystal_map etc.) was changed in v0.5, which is the reason for symmetry having to be imported via the `orix.quaternion` module.
* I changed the data directory. Although the directory used was the one I used locally, for convenience, which I didn't bother changing before because the user could do it.
demo

demo2/3: The file names here correctly correspond to the Google Drive file names, I see no issue here?

I haven't used the notebooks 2/3 with the tqdm progressbar. Could you explain what is "not working perfectly"?
