### ISSUE TITLE
Improving the clarity and accuracy of the demos by design improvements

### ISSUE THREAD

**Issue by pc494** [pyxem/orix-demos#19]
This issue is the result of a correspondence between the developers and @SteffenBrinckmann. Some of this discussion can be seen in #17.

A low hanging fruit (to be addressed in #18) is the placement of the small (<<100MB) data files, which will be moved into this repo, so that more of the demos run without separately accessing the google drive.

Beyond that, there are broadly, two approaches are under consideration:

Use Notebooks
--------------------
Currently, we use our notebooks fairly naively, and improvements could move us a long for. For example using nbviewer (as kikuchipy does) makes the "online no download" consumption of the content much quicker. Furthermore, it seems very possible that we could test our notebooks [1] and potentially convert them to .rst files [2] with only a small investment of time.

Use doctest
----------------
This route would align our documentation more closely with hyperspy, it would probably be more readable and (being basically .rst) allow more flexible discussion (science could more easily include easy-to-render latex etc), as the "conversational" style is difficult to implement in a notebook.

General Considerations
-------------------------------
Whatever solution is adopted, we want to be able to change the documentation in one place and one place only. This might require some clever filtering through of information. The eventual testing (travis, almost certainly) should be a cron job, to identify potential regression introduced by changing dependencies. As a philosophical position, I will say that I have always believed the notebooks to be documentation (and not an extension of our testing architecture) and I think a future decision should reflect that.

Tools
-------
[1] - https://pypi.org/project/nbval/
[2] - https://nbconvert.readthedocs.io/en/latest/

**Comment by SteffenBrinckmann** [comment]
Dear All, 
I pushed all files, incl. html, to my orix-demo fork/branch. It should be part of the pull request.

As regard to the notebook/rst discussion. If there are many tutorials/examples, just a plain file list in github orix-demo is helpful for the advanced, but difficult to navigate for the more novice. I guess, an overview has exist that gives context, and this overview has to be manually written. The rst files link better into this overview but also links to nbviewer could be integrated.

I agree to the concept "Change in one place only" but I don't understand contextually how "This [concept] might require some clever filtering through of information." Can you give an example?

**Comment by hakonanes** [comment]
I'll create a PR
* adding an nbviewer badge in the README
* set up nbval + Travis to see how that works

Hopefully today.

If this is easy, I'll have a go at nbconvert as well, and see if that can fit into the HTML setup of @SteffenBrinckmann, so that `.rst` files aren't created manually, which I don't want. This is because I've updated the CrystalMap notebook *many* times, and having to do the exact same change in an `.rst` file as well is extra work I don't want to do.

**Comment by hakonanes** [comment]
I'm starting to think that if we want to display the notebooks in `rst` format, we should rather display those as part of the orix rtd documentation under an "Examples" page or similar alongside the "API reference" (https://orix.rtfd.io), to keep everything easily accessible in one place.

While `nbconvert` can export a notebook to many formats, I think `nbsphinx` is what we want: https://nbsphinx.readthedocs.io/en/0.7.1/. With this I think it will be easy to display the notebooks alongside the API reference.

What do you think of this, @SteffenBrinckmann?

**Comment by pc494** [comment]
@hakonanes, did you stumble across how PyFai deals with this in your travels? It seems to me that they are doing something similar

**Comment by hakonanes** [comment]
@pc494, the https://github.com/wiai/xcdskd repository, actually.

**Comment by pc494** [comment]
I suggest someone (can be me) migrates the .rst components of #17 as well as the doctest configuration to the orix repo. We can then link the pages from here.

**Comment by hakonanes** [comment]
The things discussed here are broadly done.
