### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix-demos#26]
All demo notebooks in this repository are now part of the [orix user guide](https://orix.readthedocs.io/en/latest/?), and will be maintained there. I therefore suggest to archive this repository, which I will do once I get some confirmation from other maintainers (@pc494, @dnjohnstone).

~I consider it safe to eventually delete the repository after some time, as the only reference to it that I know of is in the orix repository's [README](https://github.com/pyxem/orix/blob/master/README.rst).~

**Comment by pc494** [comment]
I would remove almost all the content bar the README before archiving for the avoidance of doubt. The DOI means that users reading the density based clustering manuscript can still access the code as required.

**Comment by hakonanes** [comment]
I oversaw the link to this repository in the paper. This repository should never be deleted, then, only archived.

> I would remove almost all the content bar the README before archiving for the avoidance of doubt.

Good point, I'll do that.

**Comment by pc494** [comment]
> I oversaw the link to this repository in the paper. This repository should never be deleted, then, only archived.
> 
> > I would remove almost all the content bar the README before archiving for the avoidance of doubt.
> 
> Good point, I'll do that.

The link points to DOI and not the github page as far as I know. But I agree that archive first seems reasonable.

**Comment by hakonanes** [comment]
> The link points to DOI and not the github page as far as I know

It does, but the [Zenodo page](https://zenodo.org/record/3837261#.YlFaxx5ByV4) points to the GitHub repo quite clearly via the "Available in GitHub" button. Therefore, I suggest to only archive this repo.

The demo files are available on both Zenodo and via the "v0.2.3" tag in this repo, so deleting files from master is OK.

**Comment by hakonanes** [comment]
Thanks @pc494, archiving...
